; -------------------------------------------------------------------
;                        demo
; 
; Program for a TMS9X18 Color Video Card driver and Elf/OS
;
; This program uses the TMS9118 graphics mode 2 for bitmap display
; -------------------------------------------------------------------
; *** Based on software written by Glenn Jolly
; *** Original author copyright notice:
; Copyright (C) 2021 by Glenn Jolly;
; You have permission to use, modify, copy, and distribute
; this software for non commercial uses.  Please notify me 
; on the COSMAC ELF Group at https://groups.io/g/cosmacelf of any
; improvements and/or corrections.
; -------------------------------------------------------------------
; *** Uses BIOS calls from software written by Michael H Riley
; *** Original author copyright notice:
; -------------------------------------------------------------------
; *** This software is copyright 2004 by Michael H Riley          ***
; *** You have permission to use, modify, copy, and distribute    ***
; *** this software so long as this copyright notice is retained. ***
; *** This software may not be used in commercial applications    ***
; *** without express written permission from the author.         ***
; -------------------------------------------------------------------

#include    include/bios.inc
#include    include/kernel.inc
#include    include/ops.inc
#include    include/vdp.inc

; declare external procedures in library
            extrn  checkVideo
            extrn  beginG2Mode
            extrn  sendBitmap
            extrn  sendColors
            extrn  sendNames
            extrn  endG2Mode

          ; Executable program header generated by linker


          org     2000h
demo:       br      main
                              
            ; Build information    
            db      8+80h              ; month
            db      29                 ; day
            dw      2022               ; year
            dw      2                  ; build
                        
            db      'Copyright 2022 by Gaston Williams',0
                        
            
main:       CALL checkVideo
            lbdf no_driver
            
            CALL beginG2Mode  
            
            CALL sendBitmap
            dw START_BITMAP     ; START_BITMAP defined in include file
            CALL sendColors
            dw START_COLORTABLE ; START_COLORTABLE defined in include file
            CALL sendNames
            
            ldi V_VDP_KEEP      ; Set D to keep display after exit  
            CALL endG2Mode
            rtn

no_driver:  CALL O_INMSG        ; show error message
            db 'TMS9X18 Video driver is not loaded.',10,13,0
            rtn                 ; return to Elf/OS
            
#include demo.inc               ; image bitmap and color table data
          end demo
