; -------------------------------------------------------------------
;                        hello
; 
; Program for a TMS9X18 Color Video Card driver and Elf/OS
;
; This program uses the TMS9118 mode 0 for 40x24 text
 -------------------------------------------------------------------
; *** Based on software written by Glenn Jolly
; *** Original author copyright notice:
; Copyright (C) 2021 by Glenn Jolly;
; You have permission to use, modify, copy, and distribute
; this software for non commercial uses.  Please notify me 
; on the COSMAC ELF Group at https://groups.io/g/cosmacelf of any
; improvements and/or corrections.
; -------------------------------------------------------------------
; *** Uses BIOS calls from software written by Michael H Riley
; *** Original author copyright notice:
; -------------------------------------------------------------------
; *** This software is copyright 2004 by Michael H Riley          ***
; *** You have permission to use, modify, copy, and distribute    ***
; *** this software so long as this copyright notice is retained. ***
; *** This software may not be used in commercial applications    ***
; *** without express written permission from the author.         ***
; -------------------------------------------------------------------
;
;                  TMS9118
;            Text mode memory map
;            +-----------------+ 0000h
;            |  Pattern Table  |
;            +-----------------+ 0800h 2048 (can define 256 codes)
;            |    Name Table   |
;            +-----------------+ 0BC0h 3008 (40x24 960 chars)
;            |     Unused      |
;            +-----------------+ 3FFFh (16k VRAM)
;

#include    include/bios.inc
#include    include/kernel.inc
#include    include/ops.inc
#include    include/vdp.inc


#define cr  13
#define lf  10

; declare external procedures in vdp_video library
        extrn  checkVideo
        extrn  setAddress
        extrn  beginTextMode
        extrn  setTextCharXY
        extrn  writeTextString
        extrn  endTextMode


; Executable program header generated by linker

        org     2000h
hello:      br      main
            
            ; Build information            
            db      9+80h              ; month
            db      1                 ; day
            dw      2022               ; year
            dw      2                  ; build
            
            db      'Copyright 2022 by Gaston Williams',0
            
main:       call checkVideo     ; verify vdp driver is loaded in memory
            lbdf no_driver
            
            call beginTextMode  ; start text mode
            
            call setTextCharXY
            db   10, 0
            mov  rf, GREETING 
            call writeTextString

            ldi V_VDP_KEEP     ; reset the display
            call endTextMode
            rtn                ; return to monitor


no_driver:  call O_INMSG
            db 'TMS9X18 Video driver is not loaded.',10,13,0
            rtn

GREETING:  db 'Hello, World!', 0       ; 13 chars

            end hello
